### PR TITLE
expose div ref and update types for Lottie.ref

### LINKED ISSUE #110: `ref` Type incorrect
Currently the type of the `ref` prop on the `Player` component is inherited from the `HTMLDivElement`, but in the source the Lottie instance is passed to the forwarded ref.

Type inheriting here:

https://github.com/mifi/react-lottie-player/blob/66e98a12a6cae5f3dd7eb9c3c9aa2f0482e34e76/src/index.d.ts#L10-L26

Lottie ref assigned here:

https://github.com/mifi/react-lottie-player/blob/66e98a12a6cae5f3dd7eb9c3c9aa2f0482e34e76/src/makeLottiePlayer.js#L66-L70

I am happy to assist with correcting this by exposing the `animElementRef` prop and correcting the types for both if a PR would be accepted.

### PR DESCRIPTION
**Pull request by lachieh**
Closes #110 

I needed to update the `lottie-web` version to get the correct types, but I don't use `yarn` so I installed latest and it looks like it updated the lock file quite significantly. Let me know if this is not good and I'll leave the changes to `yarn.lock` off.

### CODE REVIEW

**Comment by mifi** [comment]
Thanks for the PR. Yes I tihnk you can remove all the yarn-related changed from the pr, as well as the lottie-web version change is package.json because it [doesn't do anything](https://semver.org/). I might have misunderstood but I thought the change was a TS-only fix. Why do we need to expose the `animElementRef`? Nobody requested the need for the div element to be exposed as a ref (until now). I'm not sure if we'll want that to be part of the API. What's the use case for it?

**Comment by lachieh** [comment]
Thanks, ditched the yarn changes and element ref changes. I left the function handling in with the existing ref, but can take that out too if preferred.

**Comment by mifi** [comment]
seems that something broke in the tests

**Comment by lachieh** [comment]
I'll take a look this weekend 👍

**Comment by lachieh** [comment]
Ok, sorted. Tests run successfully after failing locally so should be good for another run.

**Pull request merged**
