### PR TITLE
Adding audioFactory

### PR DESCRIPTION
**Pull request by rodbs**
Added audioFactory following the lottie-web audio feature:
https://github.com/airbnb/lottie-web/wiki/Audio

It might be needed to tweak the useEffects.

### CODE REVIEW

**Comment by mifi** [comment]
Thanks. However there's a lot of unrelated changes - need to cleanup this PR

**Comment by rodbs** [comment]
What do you mean? I only added the audioFactory functionality. I think the Prettier formatting messed everything up.

**Comment by mifi** [comment]
Ah yes. Looks like it. it's just 2 lines that you changed right?

**Comment by rodbs** [comment]
3 or 4 lines. Just look for audioFactory  (in props, in the lottie function, in PropTypes ...)

**Comment by mifi** [comment]
I have now fixed your pr

**Pull request merged**
