### PR TITLE
bump: `lottie-web`

### PR DESCRIPTION
**Pull request by afonsojramos**
@mifi

### CODE REVIEW

**Comment by mifi** [comment]
Correct me if I'm wrong but I think your change doesn't effectively do anything? due to caret `^`

**Comment by afonsojramos** [comment]
@mifi it adjusts the new minimum. But additionally, I'd say that the '^' should be removed.

**Comment by mifi** [comment]
what's the benefit of a higher minimum version? what if some people are running an older version

I'm not sure pinning the version by removing `^` is the right thing to do, as many people like to be able to update their dependencies by running yarn upgrade and similar.

**Comment by afonsojramos** [comment]
I was getting some errors in typescript due to this dependency, but I'll try to force it using npm 8's dependency forcing.

**Pull request closed without merging**
